name: reusable workflow
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  verify-docker-build:
    runs-on:
      - ubuntu-latest
      
    steps:
      - name: Echo inputs
        run: |
          echo ${{ github.event.inputs.environment }}
          
      - name: Install / Configure AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

  
